export const YFDT_GET_TABS = 'YFDT_GET_TABS';

export const YXKCK_GET_LIST = 'YXKCK_GET_LIST';
export const YXKCK_GET_LIST_PULL = 'YXKCK_GET_LIST_PULL';
export const YXKCK_GET_LIST_NOPULL = 'YXKCK_GET_LIST_NOPULL';
export const YXKCK_GET_CLASSTAL = 'YXKCK_GET_CLASSTAL';
export const YXKCK_RESET_DATA = 'YXKCK_RESET_DATA';
export const YXKCK_GET_DETAIL = 'YXKCK_GET_DETAIL';
export const YXKCK_UPDATE_ZAN = 'YXKCK_UPDATE_ZAN';
export const YXKCK_DETAIL_UPDATE_ZAN = 'YXKCK_DETAIL_UPDATE_ZAN';

export const MSG_POPUP_SHOW = 'MSG_POPUP_SHOW';
export const MSG_POPUP_HIDE = 'MSG_POPUP_HIDE';

export const LOADER_SHOW = 'LOADER_SHOW';
export const LOADER_HIDE = 'LOADER_HIDE';

export const PXB_GET_LIST = 'PXB_GET_LIST';
export const PXB_RESET = 'PXB_RESET';
export const PXB_GET_DETIAL = 'PXB_GET_DETIAL';
export const PXB_GET_TOPIC_LIST = 'PXB_GET_TOPIC_LIST';

